### ISSUE TITLE
TradingAPI `check_order()` no longer returns `free_space_new` and the 3 `transaction_XXX` properties

### ISSUE THREAD

**Issue by funnel20** [Chavithra/degiro-connector#56] opened 2022-01-06 15:35 UTC
The [create order docu](https://github.com/Chavithra/degiro-connector#41-how-to-create-an-order-) shows that the response on `check_order()` has 6 parameters. 
I did see all of them in the past, but recently it only returns:

- `confirmation_id`
- `response_datetime`

This behaviour is observed on both NASDAQ and Euronext Amsterdam.

**Comment by Chavithra** [comment] 2022-01-17 16:38
Hello @funnel20,

you are right, I think they have changed their API.

The `check_order` response looks like this now :

```json
{
    "confirmationId": "MOCK_CONFIRMATION_ID",
    "freeSpaceNew": 1.2345,
    "showExAnteReportLink": true,
    "transactionFee": 1.2
}
```

A new release let you access these new parameters.

**Comment by funnel20** [comment] 2022-01-17 17:25
Hi @Chavithra,
Thanks, I'll test it tomorrow. I see you have it assigned to me. Do you want me to update the docu?

**Comment by Chavithra** [comment] 2022-01-17 18:08
> Hi @Chavithra, Thanks, I'll test it tomorrow. I see you have it assigned to me. Do you want me to update the docu?

The assignment thing as likely no meaning except: waiting for feedback.

Your contribution is always welcome.

Thanks for letting me know about this bug.

**Comment by funnel20** [comment] 2022-01-18 09:07
@Chavithra I'd like to test the update, but `pip` doesn't have version 2.0.14:

`ERROR: Could not find a version that satisfies the requirement degiro-connector==2.0.14 (from versions: 0.0.4, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.11, 0.1.0, 0.1.1, 0.1.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.0.13)
ERROR: No matching distribution found for degiro-connector==2.0.14`

Can you please release it?

**Comment by Chavithra** [comment] 2022-01-18 14:37
> @Chavithra I'd like to test the update, but `pip` doesn't have version 2.0.14:
> 
> `ERROR: Could not find a version that satisfies the requirement degiro-connector==2.0.14 (from versions: 0.0.4, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.11, 0.1.0, 0.1.1, 0.1.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.0.13) ERROR: No matching distribution found for degiro-connector==2.0.14`
> 
> Can you please release it?

fixed

**Comment by funnel20** [comment] 2022-01-18 14:45
Cool. I'm working on improved docu for Chapter 4 (Orders). I'll send you a PR once ready for review.

**Comment by funnel20** [comment] 2022-01-18 15:38
I've tested `confirm_order()`, but only see 3 of these parameters:
```python
confirmation_id: "e2a1da94-aaaa-4f24-85c0-6c9320804534"
response_datetime {
  seconds: 1642520015
  nanos: 569196000
}
transactionFee: 2.5
showExAnteReportLink: true
```
`freeSpaceNew` is missing.

I also notice that these parameter names have camel case syntax, instead of the Pythonian underscores.

Regarding the docu, do you have any idea what `showExAnteReportLink` means?

**Comment by funnel20** [comment] 2022-01-18 16:00
> Cool. I'm working on improved docu for Chapter 4 (Orders). I'll send you a PR once ready for review.

Update is pending as PR https://github.com/Chavithra/degiro-connector/pull/59

**Comment by coveritytest** [comment] 2022-01-18 19:23
Apparently the buy price is not returned when an order is confirmed. Is there an easy way to get the buy price with the order id?

**Comment by funnel20** [comment] 2022-01-18 20:31
> Apparently the buy price is not returned when an order is confirmed. Is there an easy way to get the buy price with the order id?

When the order is confirmed, it's not executed by the exchange, so the price is not known. You can retrieve the execution price from the transaction history. Unfortunately that doesn't report the `order_id`, so you should link the order to the matching transaction. For an example, see: https://github.com/Chavithra/degiro-connector/issues/41

**Comment by funnel20** [comment] 2022-01-19 09:04
@coveritytest As indicated in the [order docu](https://github.com/Chavithra/degiro-connector#4-order), you should use parameter `stop_price` instead of `price` for `Order.OrderType.STOP_LOSS`.

**Comment by coveritytest** [comment] 2022-01-19 10:23
Thanks for your help, I'm sorry, I deleted all my comments, so can you. Then it's clean again.

**Comment by funnel20** [comment] 2022-01-30 08:12
@Chavithra Did you see my [feedback](https://github.com/Chavithra/degiro-connector/issues/56#issuecomment-1015534662)?
And can you update please?

**Comment by Chavithra** [comment] 2022-01-30 15:52
Hello @funnel20 I indeed didn’t see your feedback.

Thank you for this reminder.

Noted this point will work on it the following days.

**Comment by funnel20** [comment] 2022-01-30 16:15
@Chavithra Awesome. I already wrote the [docu](https://github.com/Chavithra/degiro-connector#411-check-order) with the Pythonian names.

**Comment by funnel20** [comment] 2022-02-06 11:48
@Chavithra I've tried to solve this for you, but I've no clue how. Especially since I have no idea where the file trade.proto is stored on my local machine.
Could you please have a look into it?

**Comment by Chavithra** [comment] 2022-02-06 18:21
Hey @funnel20,

**REPORT EX-ANTE**
When you pass an order in the website you probably have a link called like this :
- `Download the Costs and Charges Report`

I think this is the `report ex-ante`, to know the cost before confirming the order.

**FREE SPACE NEW**
I can't reproduce this issue :
- missing `free_space_new` in the response of `check_order` function.

Do you still have this issue ? if so with which product ?

Thanks

**Comment by funnel20** [comment] 2022-02-06 19:14
Hi @Chavithra . I'm using version 2.0.15 of the-connector.
I have placed orders for a Dutch stock (ABN-AMRO) and Apple (APPL) on Nasdaq.

My code for AAPL:
```python
order = Order(
    action=Order.Action.BUY,
    order_type=Order.OrderType.LIMIT,
    price=162.4,
    product_id=331868,
    size=1,
    time_type=Order.TimeType.GOOD_TILL_DAY,
)

# FETCH CHECKING_RESPONSE
checking_response = trading_api.check_order(order=order)
logging.info(checking_response)
```
This prints:

```python
2022-02-06T20:11:23.987 INFO - confirmation_id: "20033f1e-XXXXXXX"
response_datetime {
  seconds: 1644174683
  nanos: 987875000
}
transactionFee: 0.5
showExAnteReportLink: true
```

**Comment by Chavithra** [comment] 2022-02-06 19:33
Just tried this same code and can't reproduce the issue.

1/ Do you have the `Free new space` when you try the same operation on the websit ?
2/ Would it be possible to try with version 2.0.16 ?

**Comment by funnel20** [comment] 2022-02-06 20:04
1) This is what I get in check order:
<img width="344" alt="Screenshot 2022-02-06 at 21 02 29" src="https://user-images.githubusercontent.com/2139844/152699229-3cdb6b88-f278-4a0d-b34e-cffee525a0e9.png">

2) With 2.0.16 I do see the name changes of the other 2 parameters, but still no `free_space_new`:
```python
INFO - confirmation_id: "63e60fc3-921c-4976-ba14-7451c1928308"
response_datetime {
  seconds: 1644177327
  nanos: 82671000
}
transaction_fee: 2.5
show_ex_ante_report_link: true
```

However, please note that the [original name](https://github.com/Chavithra/degiro-connector/blob/main/examples/trading/order.py#L55) was `transaction_fees` (plural, see last "s") instead of `transaction_fee`.

**Comment by funnel20** [comment] 2022-02-15 10:28
@Chavithra Are you sure that you don't have an old version of the connector somewhere on your machine?
What is your raw output?

**Comment by Chavithra** [comment] 2024-01-05 14:42
The `free_space_new` seems to work in the current version.

Closing this issue for now.

Thanks

**Closed by Chavithra** 2024-01-05 14:42 UTC
Labels: bug
