### ISSUE TITLE
Options search not working optimally

### ISSUE THREAD

**Issue by fbondeaux** [Chavithra/degiro-connector#8] opened 2021-03-02 22:15 UTC
When looking for options of Shell (GB00B03MLX29) with exchange Id 1, it returns nothing but the metrics (seconds/nanos).
This is the link: https://trader.degiro.nl/trader/#/products/81642/options?exchange=1&strikeType=-1&underlying=GB00B03MLX29&optionType=-1&month=-1&year=-1&sortColumns=expirationDate%2Cstrike&sortTypes=asc%2Casc

```
request = ProductSearch.RequestOptions(
    inputAggregateTypes='',
    inputAggregateValues='',
    optionExchangeId=1,
    underlyingIsin='GB00B03MLX29',
    searchText='',
    offset=0,
    limit=100,
    requireTotal=True,
    sortColumns='name',
    sortTypes='asc',
)

# FETCH DATA
option_list = trading_api.product_search(request=request)
```

**Comment by Chavithra** [comment] 2021-03-03 10:37
Hi,

**Issue**
I can indeed reproduce this issue.

When I send this `RequestOptions` :

```python
ProductSearch.RequestOptions(
    inputAggregateTypes='',
    inputAggregateValues='',
    optionExchangeId=1,
    underlyingIsin='GB00B03MLX29',
    searchText='',
    offset=0,
    limit=100,
    requireTotal=True,
    sortColumns='name',
    sortTypes='asc',
)
```

I have the following response :
- status code : 400
- body : {'errors': [{'text': 'No corresponding model found'}]}

**Fix**
I saw that sorting was done on the following fields for `Options` :
- expirationDate
- strike

I have figured that out comparing the `RequestOptions` and the `URL` you have provided.

It seems to work, when you empty the `sortColumns` attribute like this :

```python
    sortColumns='',
```

That probably means we can't sort on the `name` field for `Options`.

I have updated the documentation accordingly.

**Question**
Does that work on your side too ?

Thanks for reporting this bug.

**Comment by fbondeaux** [comment] 2021-03-03 12:14
@Chavithra Thanks; I will check in a few hours!

**Comment by fbondeaux** [comment] 2021-03-03 20:54
Result after the request:
DEBUG:urllib3.connectionpool:https://trader.degiro.nl:443 "GET /product_search/secure/v5/options?optionExchangeId=1&underlyingIsin=GB00B03MLX29&limit=100&requireTotal=True&sortColumns=expirationDate%2Cstrike&sortTypes=asc%2Casc&intAccount=0&sessionId=6FAEA8C3D2A26CE38DB38EBE4F.prod_a_113_2 HTTP/1.1" 404 None

https://trader.degiro.nl/trader/#/products?productType=8&exchange=1&underlying=NL0000000107&strikeType=-1&optionType=-1&month=-1&year=-1&sortColumns=expirationDate%2Cstrike&sortTypes=asc%2Casc§ 

The terminal link seems different

**Comment by Chavithra** [comment] 2021-03-03 22:10
I can see you have put : 
```python
int_account=0
```

That might be the source of your error 404.

**Comment by Chavithra** [comment] 2021-03-05 16:24
I am closing this ticket since there are no more valid bugs reported.

**Closed by Chavithra** 2021-03-05 16:24 UTC
Labels: bug

**Comment by fbondeaux** [comment] 2021-04-28 11:08
@Chavithra Sorry for my late response. It does work indeed now thank you!

I have another Q: is there a shortcut with converting the output of:
`option_list = trading_api.product_search(request=request, raw=False)`
or
`product = option_list.products[0]
`
directly into dict or list? The output is now pb extension and it takes a lot of operation to have something meaningful.

Thanks and nice job!

**Comment by fbondeaux** [comment] 2021-04-28 11:46
I'll leave this package here:
https://github.com/kaporzhu/protobuf-to-dict

**Comment by Chavithra** [comment] 2021-04-28 18:04
Hello,

here are two solution to convert `message` to `dict`.

**Solution 1**
To get the result as a `dict` you can use the parameter `raw`, like this : 
```python
option_list = trading_api.product_search(request=request, raw=True)
```

**Solution 2**
You can also use the helper method called `message_to_dict`, here is an example: 
```python
import quotecast.helpers.pb_handler as pb_handler
pb_handler.message_to_dict(message=option_list)
```

**Comment by fbondeaux** [comment] 2021-04-28 18:43
Sweet man; much appreciated
