### ISSUE TITLE
Quotecast API connect fails

### ISSUE THREAD

**Issue by stathisgotsis** [Chavithra/degiro-connector#123] opened 2023-10-21 21:16 UTC
quotecast_api.connect() gets stuck with:

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): degiro.quotecast.vwdservices.com:443

but never returns (may timeout if I leave it long enough).

@Chavithra could you help on this issue?

**Comment by Chavithra** [comment] 2024-01-01 18:28
Hi @stathisgotsis,

closing this issue since it was opened a while ago and I can't reproduce it.

Feel free to open a new one if you can still reproduce it and provide more information (like the code script you try to run).

You can also join me on `discord`.

Thanks

**Closed by Chavithra** 2024-01-01 18:28 UTC
Labels: bug
